apiVersion: v1
kind: ConfigMap
metadata:
  name: easylab-config
  namespace: easylab
  labels:
    app: easylab
    component: config
data:
  PORT: "8080"
  WORK_DIR: "/app/jobs"
  DATA_DIR: "/app/data"
