apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: easylab-ingress
  namespace: easylab
  labels:
    app: easylab
    component: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik  # Adjust based on your ingress controller
  tls:
  - hosts:
    - easylab.yodamad.fr  # Replace with your actual domain
    secretName: easylab-tls
  rules:
  - host: &host easylab.yodamad.fr  # Replace with your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: easylab-service
            port:
              number: 80