apiVersion: v1
kind: Service
metadata:
  name: easylab-service
  namespace: easylab
  labels:
    app: easylab
    component: service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: easylab.yodamad.fr
    external-dns.alpha.kubernetes.io/target: "82.66.173.11"
    external-dns.alpha.kubernetes.io/ttl: "120" #optional  
spec:
  selector:
    app: easylab
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  type: ClusterIP  # Change to LoadBalancer if you want external access via cloud provider's load balancer
