[project]
name = "EasyLab"
version = "0.1.0"
description = "Easily setup your labs environments"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "zensical>=0.0.23",
]
